### PR TITLE
Add support for inner spaces within parentheses and square brackets.

### PR DESCRIPTION
**Pull request by obszczymucha**
First of all, thank you for this project!

Also fixed one failing test before adding my changes (commits are logically split).
See the test files for the expected outcomes of new formatting options.

### CODE REVIEW

**Comment by CppCXY** [comment]
First of all, there is no need to divide into two options, and pairs of space option must be selected at the same time. and then you should consider use `Add<KeepElement>(1)` instead of `Add<SpaceElement>()`

**Comment by obszczymucha** [comment]
Very good suggestion. I merged the pairs of options and gave them more reasonable names.

**Comment by CppCXY** [comment]
```lua
local t = {}
function t:fffff(
aaa
)
    local t = 13
end
```
format this code multiple times and the result is unstable

**Comment by CppCXY** [comment]
```lua
t:fffff( 1, 2, 3 )
```

codestyle check warning:   "unnecessary whitespace after operator '('"

**Comment by CppCXY** [comment]
my formatter can check code style. you can use vscode emmylua-codestyle plugin test this feature

**Comment by obszczymucha** [comment]
> ```lua
> t:fffff( 1, 2, 3 )
> ```
> 
> codestyle check warning: "unnecessary whitespace after operator '('"

Yeah that's because it's a different style. I think the user should be able to choose what style they prefer.

**Comment by obszczymucha** [comment]
> ```lua
> local t = {}
> function t:fffff(
> aaa
> )
>     local t = 13
> end
> ```
> 
> format this code multiple times and the result is unstable

I tested this with the default settings by running:
```
CodeFormat format -f test.lua
```

and with new options enabled:
```
CodeFormat format -f test.lua -c lua.template.editorconfig
```

The results are the same if I reformat multiple times. Are you sure it's not VsCode messing it up?

**Comment by obszczymucha** [comment]
Is there a way to configure VSCode to use this build for your extension for testing?

**Comment by obszczymucha** [comment]
Good catch, I was able to reproduce it. I'll try to fix it.

**Comment by CppCXY** [comment]
clone https://github.com/CppCXY/VSCode-EmmyLuaCodeStyle for vscode extension
do
```
yarn  #or npm install
```
press F5, the vscode extension will try to connect localhost's 5008 port.

you can run with `CodeFormatServer 5008`  debug with gdb or visualstudio or clangd

**Comment by obszczymucha** [comment]
I've fixed the parentheses options. I still need to verify the square brackets option and do some more testing.

**Comment by obszczymucha** [comment]
Thanks to your instructions, I was able to run the extension in vscode with my local server.
I could now see the warnings you mentioned.

All fixed now (fingers crossed :wink:).

**Pull request merged**
